export type Pattern = {
  patternName: string;
  size: number[];
  pattern: boolean[][];
};

export type PatternGroup = {
  groupName: string;
  patterns: Pattern[];
};

export const patternGroups: PatternGroup[] = [
  {
    groupName: "Still-life",
    patterns: [
      {
        patternName: "Block",
        size: [2, 2],
        pattern: [
          [true, true],
          [true, true],
        ],
      },
      {
        patternName: "Beehive",
        size: [4, 3],
        pattern: [
          [false, true, true, false],
          [true, false, false, true],
          [false, true, true, false],
        ],
      },
      {
        patternName: "Loaf",
        size: [4, 4],
        pattern: [
          [false, true, true, false],
          [true, false, false, true],
          [false, true, false, true],
          [false, false, true, false],
        ],
      },
      {
        patternName: "Boat",
        size: [3, 3],
        pattern: [
          [true, true, false],
          [true, false, true],
          [false, true, false],
        ],
      },
      {
        patternName: "Tub",
        size: [3, 3],
        pattern: [
          [false, true, false],
          [true, false, true],
          [false, true, false],
        ],
      },
    ],
  },
  {
    groupName: "Oscillator",
    patterns: [
      { patternName: "Blinker", size: [3, 1], pattern: [[true, true, true]] },
      {
        patternName: "Toad",
        size: [4, 2],
        pattern: [
          [false, true, true, true],
          [true, true, true, false],
        ],
      },
      {
        patternName: "Beacon",
        size: [4, 4],
        pattern: [
          [true, true, false, false],
          [true, false, false, false],
          [false, false, false, true],
          [false, false, true, true],
        ],
      },
      {
        patternName: "Pulsar",
        size: [15, 15],
        pattern: [
          [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
          [
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
          ],
          [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
          [
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
          ],
          [
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
          ],
          [
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
          ],
          [
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
          ],
          [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
          [
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
          ],
          [
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
          ],
          [
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
          ],
          [
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
          ],
          [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
          [
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
          ],
          [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
        ],
      },
    ],
  },
];
//   Pulsar: {
//     size: [15, 15],
//     squares: [
//       [1, 3],
//       [1, 4],
//       [1, 5],
//       [1, 9],
//       [1, 10],
//       [1, 11],
//       [3, 1],
//       [4, 1],
//       [5, 1],
//       [3, 6],
//       [4, 6],
//       [5, 6],
//       [6, 3],
//       [6, 4],
//       [6, 5],
//       [3, 8],
//       [4, 8],
//       [5, 8],
//       [3, 13],
//       [4, 13],
//       [5, 13],
//       [6, 9],
//       [6, 10],
//       [6, 11],
//       [8, 3],
//       [8, 4],
//       [8, 5],
//       [8, 9],
//       [8, 10],
//       [8, 11],
//       [9, 1],
//       [10, 1],
//       [11, 1],
//       [9, 6],
//       [10, 6],
//       [11, 6],
//       [9, 8],
//       [10, 8],
//       [11, 8],
//       [9, 13],
//       [10, 13],
//       [11, 13],
//       [13, 9],
//       [13, 10],
//       [13, 11],
//       [13, 3],
//       [13, 4],
//       [13, 5],
//     ],
//   },
// };
